server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/spms-config-repo
  application:
    name: config-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false